services:
  nginx-shop-right:
    container_name: nginx-shop-right
    image: nginx:latest
    volumes:
      - ./:/var/www/html
      - ./shop-right.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8880:80"
    networks:
      - internal
  php-shop-right:
    container_name: php-shop-right
    build:
      dockerfile: ./Dockerfile
      context: .
    volumes:
      - ./:/var/www/html
    networks:
      - internal
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - .d–∞ta/redis:/root/redis
      #- /redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
    networks:
      - internal
networks:
  internal:
    driver: bridge
